/**
 *   ______ .______   .______   .______    __  .__   __.  _______  
 *  /      ||   _  \  |   _  \  |   _  \  |  | |  \ |  | |       \ 
 * |  ,----'|  |_)  | |  |_)  | |  |_)  | |  | |   \|  | |  .--.  |
 * |  |     |   ___/  |   ___/  |   _  <  |  | |  . `  | |  |  |  |
 * |  `----.|  |      |  |      |  |_)  | |  | |  |\   | |  '--'  |
 *  \______|| _|      | _|      |______/  |__| |__| \__| |_______/ 
 * 
 * This file is generated by cppbind on 11/16/2022-12:36.
 * Please do not change it manually.
 */

#include <iostream>
#include <stdlib.h>
#include <string.h>
#include <cxxabi.h>
#include <memory>
#include <type_traits>
#include "document_scanner/api/ios/DocumentScannerFramework/DocumentScannerFramework/Cpp/cv/c_swift_types.h"
#include "DocumentScannerFramework/cppbind_wrapper_helper.hpp"
#include <opencv2/opencv.hpp>


const char* CPPBIND_CV_POINTINT = "cv::Point_<int>";
const char* CPPBIND_CV_POINTFLOAT = "cv::Point_<float>";

void release_Cv_PointInt(CppBindCObject cself, bool owner) {
    using namespace cv;
    if (owner) {
        delete static_cast<cv::Point_<int>*>(cself.ptr);
    }
    free(cself.type);
}

void release_Cv_PointFloat(CppBindCObject cself, bool owner) {
    using namespace cv;
    if (owner) {
        delete static_cast<cv::Point_<float>*>(cself.ptr);
    }
    free(cself.type);
}

